# sfsd config > config-full.yaml

default:
  server:
    host: localhost
    port: 8080
    tls:
      enabled: false
      http3: false
      cert_file: /path/to/cert.pem
      key_file: /path/to/key.pem
  directory:
    path: ./public
    allow_symlink: true
    allow_external_symlink: false
    hide_hidden: true
    rander_readme_md: false
  features:
    cors_enabled: false
    compression:
      - gzip
      - deflate
      - brotli
      - zstd
    stats_file: data/stats.json
    auth:
      enabled: false
      username: admin
      password: password123
  logging:
    format: plain
    access_log: access.log
    error_log: error.log